sonar.organization=oncontrol3d-asf
sonar.projectKey=OnControl3D-ASF_oncontrol3d-imaging-service
sonar.projectName=oncontrol3d-imaging-service

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
